#### Credit :

- https://docs.scipy.org/doc/numpy-1.13.0/user/quickstart.html

In [1]:
import numpy as np
import pandas as pd 

# 0) Data type

In [87]:
a = np.array( [ [1,2], [3,4] ], dtype=int )
a.dtype

dtype('int64')

In [102]:
a = np.array( [ [1,2], [3,4] ], dtype=np.int32 )
a.dtype

dtype('int32')

In [88]:
a = np.array( [ [1,2], [3,4] ], dtype=float )
a.dtype

dtype('float64')

In [85]:
a = np.array( [ [1,2], [3,4] ], dtype=complex )
a.dtype

dtype('complex128')

# 1) 1-D Array

### 1-0) np.linspace

In [47]:
# np.linspace(start,stop,num=50,endpoint=True,retstep=False,dtype=None)


#Return evenly spaced numbers over a specified interval.
#Returns num evenly spaced samples, calculated over the interval [start, stop].
#The endpoint of the interval can optionally be excluded.

a = np.linspace(0,30,10)
a

array([  0.        ,   3.33333333,   6.66666667,  10.        ,
        13.33333333,  16.66666667,  20.        ,  23.33333333,
        26.66666667,  30.        ])

### 1-1) np.arange

In [8]:
# np.arange(start, stop, step)

# Values are generated within the half-open interval [start, stop) (in other words, 
# the interval including start but excluding stop). 
# For integer arguments the function is equivalent to the Python built-in range function,
# but returns an ndarray rather than a list.

a = np.arange(15)
print (type(a))
print (a.dtype)

<class 'numpy.ndarray'>
int64


In [7]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [48]:
b = np.arange(0,30,10)
b

array([ 0, 10, 20])

### 1-2) np.random.randint

In [16]:
# np.random.randint(start, stop, end)

# Return random integers from low (inclusive) to high (exclusive).
# Return random integers from the “discrete uniform”
# distribution of the specified dtype in the “half-open” interval [low, high).
# If high is None (the default), then results are from [0, low).

c = np.random.randint(1,5,5)

c

array([4, 3, 4, 4, 3])

### 1-3) np.random.randn

In [32]:
# np.random.randn(d0,d1...dn)

# d0, d1, ..., dn : int, optional
# The dimensions of the returned array, should be all positive. 
# If no argument is given a single Python float is returned.

# Return a sample (or samples) from the “standard normal” distribution.
# If positive, int_like or int-convertible arguments are provided, 
# randn generates an array of shape (d0, d1, ..., dn), 
# filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1 
# (if any of the d_i are floats, they are first converted to integers by truncation). A single float randomly sampled from the distribution 
# is returned if no argument is provided.


d = np.random.randn(2,2)
print (d.shape)
d

(2, 2)


array([[ 0.35287059, -0.15142591],
       [ 0.51410057,  0.58235515]])

In [30]:
d = np.random.randn(3,3)
print (d.shape)
d

(3, 3)


array([[ 0.91954828,  0.37568995, -0.75166076],
       [-0.52968242,  1.16488721, -1.0321375 ],
       [ 0.07320897, -0.19450173,  0.21814153]])

In [28]:
type(d)

numpy.ndarray

# 2) 2-D Array

In [61]:
a = np.arange(0,20,2)
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [62]:
a.shape

(10,)

### 2-1 ) reshape 

In [75]:
# create a 2-d array (matrix) via reshape 

a = a.reshape(2,5)
print (a.shape)
a

(2, 5)


array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [67]:
# create a 2-d array (matrix) drictly 

b = np.array([(1.5,2,3,0,1), (4,5,6,1,2)])
print (b.shape)
b

(2, 5)


array([[ 1.5,  2. ,  3. ,  0. ,  1. ],
       [ 4. ,  5. ,  6. ,  1. ,  2. ]])

### 2-2) addition

In [69]:
# matrix addition
a + b

array([[  1.5,   4. ,   7. ,   6. ,   9. ],
       [ 14. ,  17. ,  20. ,  17. ,  20. ]])

### 2-3) dot 

In [71]:
# matrix dot 
np.dot(a,b.T)

array([[  24.,   56.],
       [  99.,  236.]])

### 2-4)  multiply

In [187]:
# multiply 
# via "Broadcasting", get products of elments in same position 

x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)

print (x1)
print ('')
print ('--------')
print (x2)


[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]]

--------
[ 0.  1.  2.]


In [84]:
#array([[  0*0,   1*1,  2*2],
#       [  0*0,   4*1,  5*2],
#       [  0*0,   7*1,  8*2]])


np.multiply(x1,x2)

array([[  0.,   1.,   4.],
       [  0.,   4.,  10.],
       [  0.,   7.,  16.]])

### 2-5 ) inverse matrix 

In [191]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
a

array([[ 1.,  2.],
       [ 3.,  4.]])

In [200]:
a_inv = np.linalg.inv(a)
a_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [201]:
a*a_inv 

array([[-2. ,  2. ],
       [ 4.5, -2. ]])

# 3) N- Arrays

### 3-1) zero arrays

In [89]:
a = np.zeros( (3,4) )
a

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

### 3-2) one arrays

In [90]:
b = np.ones( (3,4) )
b

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

### 3-3) identity

In [100]:
c = np.identity((3))
c

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [186]:
# or via np.eye 
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

### 3-4)  axis 

In [107]:
x1 = np.arange(9.0).reshape((3, 3))
x1

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]])

In [108]:
x1.sum()

36.0

In [109]:
# axis 0 : the "column 1"
x1.sum(axis=0)

array([  9.,  12.,  15.])

In [111]:
# axis 1 : the "row 1 "
x1.sum(axis=1)

array([  3.,  12.,  21.])

In [117]:
print (x1.min())
print (x1.min(axis=0))
print (x1.min(axis=1))  
print (x1.cumsum(axis=1)) 

0.0
[ 0.  1.  2.]
[ 0.  3.  6.]
[[  0.   1.   3.]
 [  3.   7.  12.]
 [  6.  13.  21.]]


### 3-5) universal functions

In [123]:
print (np.exp(x1))
print (np.sqrt(x1))

[[  1.00000000e+00   2.71828183e+00   7.38905610e+00]
 [  2.00855369e+01   5.45981500e+01   1.48413159e+02]
 [  4.03428793e+02   1.09663316e+03   2.98095799e+03]]
[[ 0.          1.          1.41421356]
 [ 1.73205081  2.          2.23606798]
 [ 2.44948974  2.64575131  2.82842712]]


In [158]:
def f(x,y):
    return 10*x+y

def g(x,y):
    return np.sin(x*y)

In [153]:
b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [159]:
np.fromfunction(g,(3,3),dtype=int)

array([[ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.84147098,  0.90929743],
       [ 0.        ,  0.90929743, -0.7568025 ]])

### 3-6) slicing

In [124]:
x1

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]])

In [128]:
x1[1:,:]

array([[ 3.,  4.,  5.],
       [ 6.,  7.,  8.]])

In [129]:
x1[:,:1]

array([[ 0.],
       [ 3.],
       [ 6.]])

In [139]:
x2 = np.arange(27.0).reshape((3,3,3))
print (x2.shape)
x2

(3, 3, 3)


array([[[  0.,   1.,   2.],
        [  3.,   4.,   5.],
        [  6.,   7.,   8.]],

       [[  9.,  10.,  11.],
        [ 12.,  13.,  14.],
        [ 15.,  16.,  17.]],

       [[ 18.,  19.,  20.],
        [ 21.,  22.,  23.],
        [ 24.,  25.,  26.]]])

In [134]:
x2[0,...]

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]])

In [135]:
x2[...,1]

array([[  1.,   4.,   7.],
       [ 10.,  13.,  16.],
       [ 19.,  22.,  25.]])

In [145]:
x2[:,:1,:]

array([[[  0.,   1.,   2.]],

       [[  9.,  10.,  11.]],

       [[ 18.,  19.,  20.]]])

In [160]:
for i in x2:
    print (i)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]]
[[  9.  10.  11.]
 [ 12.  13.  14.]
 [ 15.  16.  17.]]
[[ 18.  19.  20.]
 [ 21.  22.  23.]
 [ 24.  25.  26.]]


In [150]:
# flatten the N array 

for i in x2.flatten():
    print (i)

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0
11.0
12.0
13.0
14.0
15.0
16.0
17.0
18.0
19.0
20.0
21.0
22.0
23.0
24.0
25.0
26.0


### 3-7) indexing


In [180]:
x1

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]])

In [183]:
index_ = (x1>3)
index_

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [185]:
x1[x1>3]

array([ 4.,  5.,  6.,  7.,  8.])

### 3-8) newaxis

In [162]:
a = np.array([4.,2.,10,11])
a

array([  4.,   2.,  10.,  11.])

In [168]:
a_ = a[:,np.newaxis]
a_

array([[  4.],
       [  2.],
       [ 10.],
       [ 11.]])

In [177]:
b = np.array([1,2,3,4])
b

array([1, 2, 3, 4])

In [172]:
a_ * b

array([[  4.,   8.,  12.,  16.],
       [  2.,   4.,   6.,   8.],
       [ 10.,  20.,  30.,  40.],
       [ 11.,  22.,  33.,  44.]])

In [173]:
a*b

array([  4.,   4.,  30.,  44.])

In [179]:
np.multiply(a_,b)

array([[  4.,   8.,  12.,  16.],
       [  2.,   4.,   6.,   8.],
       [ 10.,  20.,  30.,  40.],
       [ 11.,  22.,  33.,  44.]])